# Generated by Django 4.2.1 on 2023-06-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=254, unique=True)),
                ('client_phone', models.CharField(max_length=20)),
                ('table_number', models.IntegerField(default=None)),
                ('number_of_guests', models.IntegerField()),
                ('reservation_time', models.TimeField()),
                ('reservation_time_end', models.TimeField()),
                ('reservation_date', models.DateField()),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmed_visit', models.BooleanField(default=False)),
                ('uidb64', models.CharField(blank=True, max_length=64)),
                ('token', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
